export const ProductData = [
    //fruits
    {
        name:'grapes',
        img:'🍇',
        price:133,
        type:'fruit',
        id:1
    },
    {
        name:'orange',
        img:'🍊',
        price:220,
        type:'fruit',
        id:2
    },
    {
        name:'watermelon',
        img:'🍉',
        price:123,
        type:'fruit',
        id:3
    },
    {
        name:'banana',
        img:'🍌',
        price:123,
        type:'fruit',
        id:4
    },
    {
        name:'apple',
        img:'🍎',
        price:123,
        type:'fruit',
        id:5
    },
    

    //vegis
    {
        name:'brinjal',
        img:'🍆',
        price:123,
        type:'fruit',
        id:6
    },
    {
        name:'carrot',
        img:'🥕',
        price:123,
        type:'fruit',
        id:7
    },
    {
        name:'potato',
        img:'🥔',
        price:123,
        type:'fruit',
        id:8
    },
    {
        name:'mushroom',
        img:'🍄',
        price:123,
        type:'fruit',
        id:9
    },
    {
        name:'cucumber',
        img:'🥒',
        price:123,
        type:'fruit',
        id:10
    },
    {
        name:'brocolli',
        img:'🥦',
        price:123,
        type:'fruit',
        id:11
    },
    {
        name:'garlic',
        img:'🧄',
        price:123,
        type:'fruit',
        id:12
    },
    {
        name:'onion',
        img:'🌰',
        price:123,
        type:'fruit',
        id:13
    },

    //meals
    {
        name:'meat',
        img:'🍖',
        price:123,
        type:'fruit',
        id:14
    },
    {
        name:'curry',
        img:'🥘',
        price:123,
        type:'fruit',
        id:15
    },
    {
        name:'ricecake',
        img:'🍙',
        price:123,
        type:'fruit',
        id:16
    },
    {
        name:'rice',
        img:'🍛',
        price:123,
        type:'fruit',
        id:17
    },
    {
        name:'sweetpotato',
        img:'🍠',
        price:123,
        type:'fruit',
        id:18
    },
    {
        name:'noodles',
        img:'🍜',
        price:123,
        type:'fruit',
        id:19
    },
    {
        name:'sushi',
        img:'🍣',
        price:123,
        type:'fruit',
        id:20
    },

    //beverages
    {
        name:'icecream',
        img:'🍨',
        price:123,
        type:'fruit',
        id:21
    },
    {
        name:'candy',
        img:'🍭',
        price:123,
        type:'fruit',
        id:22
    },
    {
        name:'cupcake',
        img:'🧁',
        price:123,
        type:'fruit',
        id:23
    },
    {
        name:'cookie',
        img:'🍪',
        price:123,
        type:'fruit',
        id:24
    },
    {
        name:'chocolate',
        img:'🍫',
        price:123,
        type:'fruit',
        id:25
    },
    {
        name:'honey',
        img:'🍯',
        price:123,
        type:'fruit',
        id:26
    },
    {
        name:'juice',
        img:'🍹',
        price:123,
        type:'fruit',
        id:27
    },

    //utensils

    {
        name:'cupplate',
        img:'🍽',
        price:123,
        type:'fruit',
        id:28
    },
    {
        name:'spoons',
        img:'🍴',
        price:123,
        type:'fruit',
        id:29
    },
    {
        name:'spoon',
        img:'🥄',
        price:123,
        type:'fruit',
        id:30
    },
    {
        name:'chopstick',
        img:'🥢',
        price:123,
        type:'fruit',
        id:31
    },
]